# Generated by Django 4.1.5 on 2023-01-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='valor',
            field=models.FloatField(),
        ),
    ]
